# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.mdiArea.sizePolicy().hasHeightForWidth())
        self.mdiArea.setSizePolicy(sizePolicy)
        self.mdiArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mdiArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.mdiArea.setViewMode(QtWidgets.QMdiArea.SubWindowView)
        self.mdiArea.setTabsClosable(False)
        self.mdiArea.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.mdiArea.setTabPosition(QtWidgets.QTabWidget.South)
        self.mdiArea.setObjectName("mdiArea")
        self.verticalLayout.addWidget(self.mdiArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuAnalysis = QtWidgets.QMenu(self.menubar)
        self.menuAnalysis.setObjectName("menuAnalysis")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDataTable = QtWidgets.QAction(MainWindow)
        self.actionDataTable.setCheckable(True)
        self.actionDataTable.setObjectName("actionDataTable")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionTileWindows = QtWidgets.QAction(MainWindow)
        self.actionTileWindows.setObjectName("actionTileWindows")
        self.actionWindows = QtWidgets.QAction(MainWindow)
        self.actionWindows.setObjectName("actionWindows")
        self.actionTile_Figures = QtWidgets.QAction(MainWindow)
        self.actionTile_Figures.setObjectName("actionTile_Figures")
        self.actionFull_Screen_F11 = QtWidgets.QAction(MainWindow)
        self.actionFull_Screen_F11.setObjectName("actionFull_Screen_F11")
        self.actionReloadScript = QtWidgets.QAction(MainWindow)
        self.actionReloadScript.setObjectName("actionReloadScript")
        self.actionLoadScript = QtWidgets.QAction(MainWindow)
        self.actionLoadScript.setObjectName("actionLoadScript")
        self.actionParameters = QtWidgets.QAction(MainWindow)
        self.actionParameters.setCheckable(True)
        self.actionParameters.setObjectName("actionParameters")
        self.actionFigure = QtWidgets.QAction(MainWindow)
        self.actionFigure.setObjectName("actionFigure")
        self.actionOpenWindows = QtWidgets.QAction(MainWindow)
        self.actionOpenWindows.setObjectName("actionOpenWindows")
        self.actionIdle = QtWidgets.QAction(MainWindow)
        self.actionIdle.setObjectName("actionIdle")
        self.menuView.addAction(self.actionTileWindows)
        self.menuView.addAction(self.actionOpenWindows)
        self.menuAnalysis.addAction(self.actionLoadScript)
        self.menuAnalysis.addAction(self.actionReloadScript)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuAnalysis.setTitle(_translate("MainWindow", "Analysis"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionDataTable.setText(_translate("MainWindow", "Data Table"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionTileWindows.setText(_translate("MainWindow", "Tile Windows"))
        self.actionTileWindows.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionWindows.setText(_translate("MainWindow", "Windows"))
        self.actionTile_Figures.setText(_translate("MainWindow", "Tile Figures"))
        self.actionFull_Screen_F11.setText(_translate("MainWindow", "Full Screen (F11)"))
        self.actionReloadScript.setText(_translate("MainWindow", "Reload Script"))
        self.actionReloadScript.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionLoadScript.setText(_translate("MainWindow", "Load Script"))
        self.actionLoadScript.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionParameters.setText(_translate("MainWindow", "Parameters"))
        self.actionFigure.setText(_translate("MainWindow", "Figures"))
        self.actionOpenWindows.setText(_translate("MainWindow", "Open Windows"))
        self.actionIdle.setText(_translate("MainWindow", "Idle"))

